{% set version = "6.7.2.42" %}
{% set build = 1 %}
{% set mpi = "openmpi" %}  # force this ... for now?
{% set mpi_prefix = "mpi_" + mpi %}
{% set build_pin = mpi_prefix + '_*' %}

package:
  name: casatools
  version: {{ version }}

source:
  fn: casa-{{ version }}.tar.gz
  url: https://open-bitbucket.nrao.edu/rest/api/latest/projects/CASA/repos/casa6/archive?at=refs%2Ftags%2F{{ version }}&format=tgz
  sha256: 5bcdfc745878fe1bb2ba57c6f6ecc587fb5a6da4371faeaa8b396560778590dc
  patches:
    - macos-not-gcc.patch  # [osx]

build:
  number: {{ build }}
  skip: true  # [win]
  string: {{ mpi_prefix }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake <4
    - ninja
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - make
    - swig
    - openjdk
    - pkg-config
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
  host:
    - {{ mpi }}
    - casacore >=3.7 {{ mpi_prefix }}_*
    - casacpp {{ version }} {{ mpi_prefix }}_*
    - libgomp      # [linux]
    - libxml2-devel
    - llvm-openmp  # [osx]
    - numpy
    - pip
    - python
    - readline
    - setuptools
    - swig
    - xerces-c
  run:
    - {{ mpi }}
    - casaconfig
    - python

test:
  imports:
    - casatools
    - casatools.__casac__
    - casatools.__casac__.agentflagger
    - casatools.__casac__.atcafiller
    - casatools.__casac__.atmosphere
    - casatools.__casac__.calanalysis
    - casatools.__casac__.calibrater
    - casatools.__casac__.componentlist
    - casatools.__casac__.coordsys
    - casatools.__casac__.functional
    - casatools.__casac__.imagemetadata
    - casatools.__casac__.imagepol
    - casatools.__casac__.image
    - casatools.__casac__.imager
    - casatools.__casac__.iterbotsink
    - casatools.__casac__.linearmosaic
    - casatools.__casac__.logsink
    - casatools.__casac__.measures
    - casatools.__casac__.miriadfiller
    - casatools.__casac__.msmetadata
    - casatools.__casac__.ms
    - casatools.__casac__.mstransformer
    - casatools.__casac__.msuvbinner
    - casatools.__casac__.quanta
    - casatools.__casac__.regionmanager
    - casatools.__casac__.sakura
    - casatools.__casac__.sdm
    - casatools.__casac__.sidebandseparator
    - casatools.__casac__.simulator
    - casatools.__casac__.singledishms
    - casatools.__casac__.spectralline
    - casatools.__casac__.synthesisdeconvolver
    - casatools.__casac__.synthesisimager
    - casatools.__casac__.synthesisimstore
    - casatools.__casac__.synthesismaskhandler
    - casatools.__casac__.synthesisnormalizer
    - casatools.__casac__.synthesisutils
    - casatools.__casac__.table
    - casatools.__casac__.tablerow
    - casatools.__casac__.utils
    - casatools.__casac__.vlafiller
    - casatools.__casac__.vpmanager
    - casatools.__casac__.wvr

about:
  home: http://casa.nrao.edu/
  license: LGPL-2.1-or-later
  license_file: casatasks/src/LICENSE.txt
  summary: "Python tool implementations for CASA, the radio astronomical data processing package"

extra:
  recipe-maintainers:
    - pkgw
